substitutions:
  name: xiaomi-philips-light

esphome:
  name: ${name}
  platform: ESP8266
  board: esp_wroom_02
  includes:
    - xiaomi_light.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
ota:

logger:
  esp8266_store_log_strings_in_flash: false

output:
  - platform: esp8266_pwm
    pin: GPIO12
    id: output_cw
  - platform: esp8266_pwm
    pin: GPIO15
    id: output_ww

light:
  - platform: custom
    lambda: |-
      auto light_out = new XiaomiLight(id(output_cw),id(output_ww));
      App.register_component(light_out);
      return {light_out};
    lights:
      - name: ${name}
        id: bulb
        gamma_correct: 0
        default_transition_length: 350ms
